spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}